---
- name: Create two ec2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-08962a4068733a2b6  
      private_subnet_id: subnet-d9d63fa4
      keypair: aws_key 
  tasks:
    - name: Create two  ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default  
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 2
         assign_public_ip: yes
         vpc_subnet_id: "{{ private_subnet_id }}"
      register: ec2

    - debug:
         var: ec2.instances[0].public_ip,ec2.instances[1].public_ip

    - name: Wait for instances to listen on port 22
      wait_for:
         state: started
         host: "{{ ec2.instances[0].public_dns_name }}"
         port: 22

    - name: Update inventory add build
      add_host:
         hostname: "{{ ec2.instances[0].public_ip }}"
         groups: build
    - name: Update inventory add prod
      add_host:
         hostname: "{{ ec2.instances[1].public_ip }}"
         groups: prod

- name: Create BUILD environment 
  remote_user: ubuntu
  hosts: build 
  become: yes
  become_user: root
  vars: 
      volume_name: vweb-app
      volume_path: "/var/lib/docker/volumes/{{ volume_name }}/_data/"
  tasks:
    - name: Ensure docker is present 
      apt:
         name: docker.io
         state: present
         update_cache: yes

    - name: Pull image build
      command: "docker pull vmdocker2022/ansiblaws_hw13"

    - name: Run container BUILD
      command: "docker run -it --name hw13_container_build -d \
      --mount type=volume,source={{ volume_name }},target=/home/user/target vmdocker2022/ansiblaws_hw13"      

    - name: Copy artifact from BUILD ENV to localhost
      synchronize:
         mode: pull
         src: "{{ volume_path }}/hello-1.0.war"
         dest: /home/user

 
- name: Create PROD environment
  remote_user: ubuntu
  hosts: prod
  become: yes
  become_user: root

  tasks:
    - name: Ensure docker is present
      apt:
         name: docker.io
         state: present
         update_cache: yes

    - name: Pull image PROD
      command: "docker pull vmdocker2022/ansiblaws_hw13_prod"

    - name: Run container PROD
      command: "docker run -it --name hw13_container_prod -d \
      -p 8080:8080 -v /home/user2:/usr/local/jetty/demo-base/webapps vmdocker2022/ansiblaws_hw13_prod"

    - name: Copy artifact from local to PROD ENV
      synchronize:
         src:  /home/user/hello-1.0.war
         dest: /home/user2
© 2021 GitHub, Inc.